### PR TITLE
[i18n] Textdomain fix according to wp.org slug

### LINKED ISSUE #5: [i18n] Textdomain doesn't match the plugin slug
Hi @marcbelletre,

Congrats for this amazing plugin :)

I was translating it in wp.org and the files `acf-rrule-xx_XX.po/.mo` aren't being loaded from the wp-content/languages folder.
The issue is that the textdomain wp.org is using to name the files is `'acf-rrule-field'` and not `'acf-rrule'`.

You should rename the textodomain to `'acf-rrule-field'` so that all translations are properly loaded, and of course, if you want to load local .po/.mo files, also rename it to `acf-rrule-field-xx_XX.po/.mo`.

Would you like a PR with this fix?

Thanks :-)

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Fixes #5

### CODE REVIEW

**Review by marcbelletre — COMMENTED** [review]
Hi Pedro,

Thank you so much for your help! 
I merged your PR but I do have one question: I used the `acf` textdomain on purpose for some translations strings because they are already translated in the ACF core. Do you think it's a bad idea to rely on the translations from another plugin?

**Comment by pedro-mendonca** [comment]
Hi :)
Generally is a bad practice, those strings are available for translators in [translate.wp.org](https://translate.wordpress.org/projects/wp-plugins/acf-rrule-field/) to translate, its translation should come from your plugin, not 3rd party.
Imagine that ACF core change that string, you will left out that update. It's better to have full control on your strings :)

**Comment by marcbelletre** [comment]
Sure, you're absolutely right.
Thanks again! I will push to the Wordpress SVN in a few minutes. Would you like to be added as a contributor for the plugin by the way? :)

**Comment by pedro-mendonca** [comment]
Not important, it's up to you, it's ok for me, thanks :)

**Comment by marcbelletre** [comment]
I updated the SVN earlier but the translation strings I added in the last release are not showing up on [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/acf-rrule-field/dev/fr/default/) although they exist in the plugin's local PO file. These translations are even working when the plugin is activated in a Wordpress installation.

Is it because the main file should also be named `acf-rrule-field.php` instead of `acf-rrule.php`?

Sorry I am new to translating stuff in Wordpress :)

**Comment by pedro-mendonca** [comment]
What are the new strings from v1.1.1?

**Comment by pedro-mendonca** [comment]
The only change I found was in a fr_FR local translation file:
https://github.com/marcbelletre/acf-rrule/commit/ceafe92a5c74e3ddaaec01110f16498ac206d875#diff-97c277b14b30d0b79149e4ee5f3003541e825cbd7208930f09319279a734f031R305

You didn't change any source string.

Do you mean the French translation?

**Comment by marcbelletre** [comment]
Sorry, the new strings are actually from v1.1 so it must have nothing to do with your changes.

The strings I am talking about are all the french translations marked as "waiting" here: https://translate.wordpress.org/projects/wp-plugins/acf-rrule-field/dev/fr/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting
They are marked as "waiting" because I uploaded the last PO file directly on translate.wordpress.org but they were marked as "untranslated" before.

These translations exist in the SVN: https://plugins.svn.wordpress.org/acf-rrule-field/tags/1.1.1/lang/acf-rrule-field-fr_FR.po
You can see for instance all the translations for the validation strings in the last lines of the file, which Wordpress consider untranslated.

Anyway unless you have any idea what's going on I will dig into this myself as it seems unrelated with your changes ;)

**Comment by pedro-mendonca** [comment]
Ok I understand now.

There are 2 separate ways to provide translation for a wp.org hosted plugin.
- Local files (as you have for fr_FR)
- Community translation from translate.wp.org

A few years ago the local files where the primary source, currently, if there are both, the wp.org provided translations are located in wp-content/languages/ and have priority on loading. WordPress first try to get these, only if there aren't any it will go look for local files on the plugin folder (through `load_plugin_textdomain()`)

What you see in wp.org (waiting, fuzzy, current, etc) are community translations, and rely on a Translation Editor to approve, according to it's locale team translation guide. As you can see, French was already fully translated (and approved!). These are entirely independent of your provided local files that you can even delete now.
Well, with a little undocumented exception: I'm almost sure that when you push a new plugin that already includes local language files, these are imported to populate the translations table db as approved!

Also, for you to receive a specific translation of your plugin from wp.org translation tables, it's status must be at least 80%. Until then you have to get it manually. After the 80% are reached, in about 30min wp.org will generate a language pack that is downloaded to your install, independently of any plugin updates.

So, if you don't plan to provide any alternate install (as with Composer) and you plan your plugin to be installed from wp.org only, you can remove your local translation files.
The strings on the wp.org translation tables are parsed directly from the code (gettext functions) on each new commit you do for trunk (dev) or tag (stable).

Hope I've helped :-)

**Comment by marcbelletre** [comment]
Hi Pedro,

Thank you very much for this very clear explanation :)

I asked the french Slack channel yesterday and they approved all my translations on translate.wp.org. They also told me that the local PO files were no longer needed but didn't provide as much details as you did.

I can confirm that on the first commit the local PO files were used to populate translations. The only strings that were loaded on translate.wp.org were the ones from the very first release.

I will leave the french translations in the Github repository for now but I may delete them from the SVN repository as they are not used anymore ;)

Thanks again for your time, you were very helpful!

**Pull request merged**
